version: "3.9"

services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: python src/manage.py wait_for_db && migrate && runserver # && tail -f /dev/null
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 15000:15000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=scutesdb
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=localhost
      - DB_PORT=5432
  
volumes:
  postgres_data:
  static-data:
