[project]
name = "scutes"
description = "Item Processing Application for WHCA Pool Reports Collection"
version = "0.0.1dev"
requires-python = ">=3.11"
license = {text = "Apache-2.0 license"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "django",
    "pathlib",
<<<<<<< HEAD
    "crispy-bootstrap5",
    "django-bootstrap5",
    "django-crispy-forms",
=======
    "django-bootstrap3",
    "django-environ",
>>>>>>> cda2f78a167dd5c18ff3dc7bb65ec894e638bd50
    "django-tables2",
    "django-filter",
    "emoji",
    "html-sanitizer",
    "Pillow",
    "psycopg2-binary",
    "mailbox",
]
[project.optional-dependencies]
dev = [
    "docutils",
    "pycodestyle",
    "pytest",
    "pytest-datadir",
    "pytest-django",
    "pytest-selenium",
    "pyyaml",
    "selenium",
    "logging",
]
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'scutes.settings'
python_files = ['tests.py', 'test_*.py']
pythonpath = ['src', '.']
markers = [
    "webdriver: marks tests that require webdriver(deselect with '-m \"not webdriver\"')",
]
[project.scripts]
"manage.py" = "scutes:django_manage"